# build stage
FROM node:20-alpine AS builder

WORKDIR /app

COPY package*.json ./


# production stage
FROM node:20-alpine

WORKDIR /app

ENV NODE_ENV=local

COPY package*.json ./
RUN npm install

COPY . .

EXPOSE 5000

USER node

CMD ["node", "index.js"]