name: Deploy

on:
  push:
    branches:
      - master
  workflow_dispatch:

permissions:
  issues: write

jobs:
  manual-approval:
    name: Manual Approval
    runs-on: ubuntu-latest

    steps:
      - name: Wait for approval
        uses: trstringer/manual-approval@v1

        with:
          secret: ${{ secrets.GITHUB_TOKEN}}
          approvers: Nydonid

  deploy:
    runs-on: self-hosted
    name: Deploy
    needs: manual-approval
    timeout-minutes: 10

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy env file
        run: cp /root/myWebsite/server/.env.production server/.env.production

      - name: Fix acme.json permissions
        run: touch acme.json && chmod 600 acme.json

      - name: Build and deploy
        run: docker compose -f docker-compose.prod.yaml up --build -d