name: Deploy to Production

on:
  push:
    branches: [ "main" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: production

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_KEY }}" > ~/.ssh/key
          chmod 400 ~/.ssh/key

      - name: Deploy to prod via SSH
        run: |
          ssh -i ~/.ssh/key -o StrictHostKeyChecking=no \
            ${{ secrets.USER }}@${{ secrets.HOST }} "
              cd ~/myWebsite &&
              docker compose pull &&
              docker compose down &&
              docker compose up -d --remove-orphans
            "